OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Parma
    Domain: parma.com
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: Brescia
    Domain: brescia.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
