version: '2'

networks:
    fabric-network:

services:
  orderer.example.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
     - fabric-network
  
  couchdb0:
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    container_name: couchdb0
    networks:
      - fabric-network

  peer0.parma.com:
      container_name: peer0.parma.com
      extends:
        file: base/docker-compose-base.yaml
        service: peer0.parma.com
      environment:
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      depends_on:
        - orderer.example.com
        - couchdb0
      networks:
        - fabric-network
  
  couchdb1:
      image: couchdb:3.2
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=adminpw
      ports:
        - 5985:5984
      container_name: couchdb1
      networks:
        - fabric-network

  peer0.brescia.com:
      container_name: peer0.brescia.com
      extends:
        file: base/docker-compose-base.yaml
        service: peer0.brescia.com
      environment:
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      depends_on:
        - orderer.example.com
        - couchdb1
      networks:
        - fabric-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.parma.com:7051
      - CORE_PEER_LOCALMSPID=ParmaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parma.com/peers/peer0.parma.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parma.com/peers/peer0.parma.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parma.com/peers/peer0.parma.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parma.com/users/Admin@parma.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.parma.com
      - peer0.brescia.com
    networks:
      - fabric-network

  # cli.brescia:
  #   container_name: cli.brescia
  #   image: hyperledger/fabric-tools:2.4
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     #- FABRIC_LOGGING_SPEC=DEBUG
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=peer0.brescia.com:7051
  #     - CORE_PEER_LOCALMSPID=BresciaMSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brescia.com/peers/peer0.brescia.com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brescia.com/peers/peer0.brescia.com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brescia.com/peers/peer0.brescia.com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brescia.com/users/Admin@brescia.com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: /bin/bash
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ./chaincode/:/opt/gopath/src/github.com/chaincode
  #     - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #     - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #   depends_on:
  #     - orderer.example.com
  #     - peer0.parma.com
  #     - peer0.brescia.com
  #   networks:
  #     - fabric-network