version: '2'

networks:
    fabric-network:
services:
  tls.ca.brescia.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true            
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_NAME=tls.ca.brescia.com
      - FABRIC_CA_SERVER_CSR_CN=tls.ca.brescia.com
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b tlsadmin:tlsadminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/brescia.com/tls.ca:/etc/hyperledger/fabric-ca-server
    container_name: tls.ca.brescia.com
    networks:
      - fabric-network
  
  tls.ca.parma.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true     
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CA_NAME=tls.ca.parma.com
      - FABRIC_CA_SERVER_CSR_CN=tls.ca.parma.com
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b tlsadmin:tlsadminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/parma.com/tls.ca:/etc/hyperledger/fabric-ca-server
    container_name: tls.ca.parma.com
    networks:
      - fabric-network

  tls.ca.orderer.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true            
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_CA_NAME=tls.ca.orderer.example.com
      - FABRIC_CA_SERVER_CSR_CN=tls.ca.orderer.example.com
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b tlsadmin:tlsadminpw'
    #command: tail -f /dev/null
    volumes:
      - ./fabric-ca/orderer.example.com/tls.ca:/etc/hyperledger/fabric-ca-server
    container_name: tls.ca.orderer.example.com
    networks:
      - fabric-network