version: '2'

services:
  peer-base:
      image: hyperledger/fabric-peer:2.4
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_CFG_PATH=/etc/hyperledger/peercfg
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-custom-network_fabric-network
        - FABRIC_LOGGING_SPEC=INFO
        #- FABRIC_LOGGING_SPEC=DEBUG
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=false
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        - CORE_PEER_GOSSIP_USELEADERELECTION=false
        - CORE_PEER_GOSSIP_ORGLEADER=true
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        #- CORE_PEER_ID=peer0.org1.example.com
        #- CORE_PEER_ADDRESS=peer0.org1.example.com:7051
        #- CORE_PEER_LISTENADDRESS=0.0.0.0:7051
        #- CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
        #- CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
        #- CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
        #- CORE_PEER_LOCALMSPID=Org1MSP
        #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
        #- CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9444
        #- CORE_METRICS_PROVIDER=prometheus
        #- CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
        #- CORE_CHAINCODE_EXECUTETIMEOUT=300s
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: peer node start